name: flutter_154620
description: "A repro for https://github.com/flutter/flutter/issues/154620"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-200.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_static: ^1.1.3

flutter:
  uses-material-design: true
